travis:
  secure:
    BINSTAR_TOKEN: LV9Ou767lTH/by34bjWhrGQquFV2Hibi3lwDclb7PbSoU9Gq4FZ4Al7yGibcVzDsEaPUcE+p6oEkihE9t4PSxzSXhMhG/FgU+Hwnpt61FU5pVxCXhfewEvYzOWA7/WOLaGkBjefyXvJ09iuxmlSy8Lf/qKrbZAKwdfEZfLwXGSPjhC291o51gSKcLy5JBiPpMkuoxZGA+m6bAIMsQ78eK22gwpPEjCTghU3xdHzkAH0m+kO364OqSfKvTr2KwwahTSa9M2BZQu032fN0Qs56PtKNql0/SIRuCBws7C8nURmhnXMOScc2p2jfF9dsbrerrz7glq7m9lioMV8B2O31PNtp/+BOJy4guw4fQQzYMBx6T7XQUJ4SuJC+lrPCepz7OnGtAZYNa+bmworQ/i6Xfc7feqrkFZcuzHLtyMTvYTTg+cZGsx4txiiQNGhDCFJ+ebrh38NZWA2eFPxZg4yN2jAGtK2SzIBMn9dISSHiJW7Wuha0vCuoJYHZtXSL8d+EiB1le1SRrzxJ9+bkEdt54E8tCA3Qz909qqYCZAaPlHmEUoZYb11VECkQLwmYeNUTORVUxNNgU7dcGGAUCt6X0Ll2lElmh5QPm6BMrfSLtDEbJTF1+Fg82qFcdvDCUE/JgpfTKLjzuVxDsumTrJWQVAqTLzY4XFcQhEgArUelpwI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
