travis:
  secure:
    BINSTAR_TOKEN: nmN5HUxIEve48PT2J+as2bmRQJAUZR91RMyUR9VfBfS3L5iOG9CEW10a3orprZaPnivt9XHmPtYqvuGvguJWaj12wU9gVi+/m2OZnvbhfwgT7jAyqU4ExG/MtYzZBB3bIayAMNyH33qirJBpm0FfvqNbkBRllJfNZopYAM5TvwTWZyC6795m47guNKl/eGC2Teh1b875/g70dvGhBr2pNwmc+ho9Ai1lM++E896U/0RWSXZCZvuwTfzHE1feSm5A3ES/6LrmJfMX6Yg/JRhr85YtqEc482HzK84O4i34WTc0KeM7LIfks54e4bC9sGdno4s2f/GHWJJlnuhhhRRjCWSpM8whxH9g+Xxy2YguqjHfG7mGqZECWYX4CTy8TqzErNlxYhKMhOW34Eay6aL8gErxidu2cx9aDadZtTJre6oSBVb14/8UtFvR0M21NBzxrBx2p5dfrbJIyPM6fXfOBcLmbLgW7My0TPTWX5E95sXPjPAHcGieE+K3q+P+4EAt7CPA/aSg+Hvlux8EFTBt0Oofvp5BZSyQKYc1ty0hrpDjH9IT/8UWGMKn3EKoUzS+OCTgGEnHi6skHQOjIJrEUNOicXtZsddIBTincvF+/QZ0o0P9TqDUDfblWQ4FBqQTSf0uoo7vfSDuh1TbcWUfs2Cdi/GtWRe6Ft77zk24Jds=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
