travis:
  secure:
    BINSTAR_TOKEN: h5UHHlGoSLU+7ymByZwc1heGsEC/dChfIPIkupwI1+7tFShgrtEmrMKGvVPv7qm8uKw19DST+JYPgsuRuPZST9dvBQK8LRu+rlFXVJ4p5bL1W0uAw9M5GcnITnx56e9SYD2nYOYbKgvbtc1y+XK9pqTTr/vh6d8qd+ev/w/PvocsU0sZn226/Gt236gUNyX8d7dovg1T66mnts9HWDKYwtJaRuM37c6dPMIrNymBTN5FXKLTyC2wv6RXvtaWSKHwJa5aXXrIKy3Y+YB2QQGoutyFQZfRgpWOMKZ7O2aRP/T2QcxwBootIPzCd10KBSKsLOYJFonen3oIzAf3yZiR02OsNRENUf+r9xc9xtxO6JXK+Jg0LxvXOchDCGxFw+cjsA1MLNaet581zaXYPxR5/Mq3yvcoXTJJQQZfSp79WpL2rWUYk6ePzOb6FV37CIDctR4fpr0Nykd4MUC2Gow9+VIw1NSN4k0jt7RTzEUKClbe9XXXegAvrmryR9HAAjnOw0sCpD6THtfhyefQ+6QVWVu0Qwuz6PhbqrqAIl/AM/dhk90lNFNbeTTozpb+vwJHssj47IDFEpeLdXVdgdpOywBn7jId8MoKS3dybXn+JIpx0n9FVue3N7WcYZqXdFkJ8s1Z94MLY8BusjOLZ5SBGq68knXxgoKXxEp63qfuIg4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
