travis:
  secure:
    BINSTAR_TOKEN: PtN7pwthSE50H0sdm5hVXkSqxjwhFO/G1EHp+vz/LddvnnP7JTLVqzFJ1gLrOXKvXkbmRKbjWKgM6qNUA+bHIIVZ3LFwRPct0+l1yfF0/VDEnXZzuggeypzCZ/IWKzc6+unhVS66JMjAAFHFqxbm2eEVsXN3nchygdOODJUuRn9nskbzNnsNuoYnHZ/8PhMpDHYuheAeOfcFzGDEHqqemueZh3u+gwq13eydjIU2Yvd42bp+4npV0WzawNRVs1lnyWZcH6U/a7jwxWT6emdmTiky+aO0ano39a0CwtQC442mHv22+MAsR/4tShuqmYwzyxQpLTZRERNdau7DtLcuRNlgWur3Z7bv1I0JcxK3wmsqvtRaQ/wBTqF0eH9RHp6QoJ3dxr9Whb4MuHBkMITC6r5aLUZVDoVqbW11RsqEW9bFtgMN+ObkjKVJNRslnnvvNyZKNcmdfzq/S88PR+J5yX/ulkAls5suPSgqpr1dWqFf3aP3ZqBCgZ86yw2tlcJIxGec87UEUVidAitIEBt+/o/Rfe1xZzztLZgJ9BgxWcwvSyorc3CHtepRwgdGWOsfqGP3E028py5cWakM6Jb9RozSmbqFMIe6BtOrjzBfoHOWZ4NzSW9QQlp6Vkxhr9Ft6kcHqNNCG0qqXyvezDRcr4rvSwlnqEuDXNu+QGHsTb4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
